name: base
channels:
  - conda-forge
dependencies:
  - archspec=0.2.5=pyhd8ed1ab_0
  - boltons=25.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py312hbb81ca0_4
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.10.5=h4c7d964_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=25.9.1=py312h2e8e312_0
  - conda-libmamba-solver=25.4.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - cpp-expected=1.3.1=h477610d_0
  - distro=1.9.0=pyhd8ed1ab_1
  - fmt=12.0.0=h29169d4_0
  - frozendict=2.4.6=py312he06e257_1
  - gh=2.83.0=h36e2d1d_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py312h2e8e312_2
  - krb5=1.21.3=hdf4eb48_0
  - libarchive=3.8.2=gpl_h26aea39_100
  - libcurl=8.16.0=h43ecb02_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libiconv=1.18=hc1393d2_2
  - liblzma=5.8.1=h2466b09_2
  - libmamba=2.3.3=h5fbfb43_1
  - libmambapy=2.3.3=py312hc175272_1
  - libsolv=0.7.35=h8883371_0
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libzlib=1.3.1=h2466b09_2
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - mamba=2.3.3=h18d3f89_1
  - menuinst=2.4.1=py312hbb81ca0_0
  - miniforge_console_shortcut=1.0=h57928b3_0
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py312he06e257_3
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.12=h0159041_1_cpython
  - python_abi=3.12=8_cp312
  - reproc=14.2.5.post0=h2466b09_0
  - reproc-cpp=14.2.5.post0=he0c23c2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - ruamel.yaml=0.18.16=py312he06e257_0
  - ruamel.yaml.clib=0.2.14=py312he06e257_0
  - setuptools=80.9.0=pyhff2d567_0
  - simdjson=4.0.7=h49e36cd_0
  - tk=8.6.13=h2c6b04d_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - truststore=0.10.3=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - yaml-cpp=0.8.0=he0c23c2_0
  - zstandard=0.25.0=py312he5662c2_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - cfgv==3.4.0
      - distlib==0.4.0
      - filelock==3.20.0
      - identify==2.6.15
      - nodeenv==1.9.1
      - pre-commit==4.4.0
      - pyyaml==6.0.3
      - virtualenv==20.35.4
prefix: C:\Users\imansaray\AppData\Local\miniforge3
